packages:
  - "packages/*"

# Define a catalog of version ranges.
catalog:
  ziko: ^1.10.0
  vite: ^8.2.1

# Wait at least 7 days before installing newly published package versions.
minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - ziko@1.10.0

# Prevent transitive dependencies from being installed from untrusted sources.
blockExoticSubdeps: true

# Prevent malicious package updates from downgrading security settings.
trustPolicy: no-downgrade
